version: "3.8"

services:
  mqtt-broker:
    image: emqx/emqx:5.3
    container_name: emqx
    ports:
      - "1884:1883"   # MQTT
      - "18083:18083" # Dashboard
    healthcheck:
      test: ["CMD", "emqx", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  sparkplug-webservice:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sparkplug-webservice
    depends_on:
      mqtt-broker:
        condition: service_healthy
    environment:
      - MQTT_HOST=mqtt-broker
      - MQTT_PORT=1883
    ports:
      - "8000:8000"
